### PR TITLE
Keycloak client

### PR DESCRIPTION
**Pull request by secondsun**

### CODE REVIEW

**Comment by pmdarrow** [comment]
Looks like snapscreen/keycloak-client branch is out of date with master and which means this PR is too. Do you mind creating a snapscreen/keycloak branch and pushing directly to that? I think would be cleaner and would enable me to go do this kind of rebasing without having to get access to your fork.

**Review by pmdarrow — CHANGES_REQUESTED** [review]
Looks like snapscreen/keycloak-client branch is out of date with master and which means this PR is too. Do you mind creating a snapscreen/keycloak branch and pushing directly to that? I think would be cleaner and would enable me to go do this kind of rebasing without having to get access to your fork.

**Comment by secondsun** [comment]
It shouldn't be out of date unless someone force pushed to master...

**Comment by damienomurchu** [comment]
Code looks and runs fine, just pulled and ran it in android emulator & redirects to github oauth & back again

**Comment by pmdarrow** [comment]
Also, any chance you can separate PRs for push and keycloak? It's hard to tell to which changes correspond with each feature when they're a single PR.

**Comment by secondsun** [comment]
@pmdarrow Nope, not going to make two PRs.  You can review the Push commit and the Keycloak commit separately.

**Comment by secondsun** [comment]
closing pr in favor of the local rebased PR

**Pull request closed without merging**
